# This workflow will build a hugo project with bundle

name: Testing For PRs

on: [ pull_request ]

env:
  NOKOGIRI_USE_SYSTEM_LIBRARIES: 1
  RUN_EXTERNAL_CHECKS: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true # would run bundle install
      - name: Run the build
        run: bundle exec rake static_checks:all
